name: Publish Documentation

on:
  workflow_dispatch:

env:
  WYAM_ACCESS_TOKEN: ${{ secrets.API_TOKEN }}
  # secrets.GITHUB_TOKEN has no permissions to push, sadly.
  WYAM_DEPLOY_BRANCH: 'gh-pages'
  WYAM_DEPLOY_REMOTE: "${{ github.event.repository.html_url }}"

jobs:
  cake:
    runs-on: ubuntu-22.04

    steps:
    - name: checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Fetch all tags and branches
      run: git fetch --prune --unshallow

    - name: Cache Tools
      uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319 # v4
      with:
        path: tools
        key: ${{ runner.os }}-doc-tools-${{ hashFiles('recipe.cake') }}

    - name: Publishing documentaiton
      uses: cake-build/cake-action@a6eb054329257c9e70a6c6bf01747ad6e1d9d52b # v1
      with:
        script-path: recipe.cake
        target: Force-Publish-Documentation
        verbosity: Diagnostic
        cake-version: tool-manifest
